// Usage: Preview / demo data for the Home page empty-state previews (DEV mode only).
// Extracted from HomeRequestLogsPanel to keep the component file lean.

import { GatewayErrorCodes } from "../../constants/gatewayErrorCodes";
import type { ClaudeModelMapping } from "../../services/gateway/claudeModelMapping";
import type { GatewayAttemptEvent } from "../../services/gateway/gatewayEvents";
import { createRequestLogSummary } from "../../services/gateway/requestLogFixtures";
import type { CliSessionsFolderLookupEntry } from "../../services/cli/cliSessions";
import type { RequestLogSummary } from "../../services/gateway/requestLogs";
import type { TraceSession } from "../../services/gateway/traceStore";

function buildClaudeModelMappingPreview(
  requestedModel: string,
  effectiveModel: string,
  mappingKind: string,
  providerId: number,
  providerName: string
): ClaudeModelMapping {
  return {
    requestedModel,
    effectiveModel,
    mappingKind,
    providerId,
    providerName,
    applied: true,
  };
}

function buildClaudeModelMappingSpecialSettingsJson(mapping: ClaudeModelMapping): string {
  return JSON.stringify([
    {
      type: "claude_model_mapping",
      scope: "attempt",
      applied: mapping.applied,
      providerId: mapping.providerId,
      providerName: mapping.providerName,
      requestedModel: mapping.requestedModel,
      effectiveModel: mapping.effectiveModel,
      mappingKind: mapping.mappingKind,
    },
  ]);
}

export function buildPreviewRequestLogs(
  nowSec = Math.floor(Date.now() / 1000)
): RequestLogSummary[] {
  const claudeFastMapping = buildClaudeModelMappingPreview(
    "claude-sonnet-4",
    "gpt-5.4",
    "sonnet",
    18,
    "Claude Fast"
  );
  return [
    {
      id: 900010,
      trace_id: "preview-claude-fast",
      cli_key: "claude",
      session_id: "claude-preview-alpha",
      method: "POST",
      path: "/v1/messages",
      requested_model: "claude-sonnet-4",
      status: 200,
      error_code: null,
      duration_ms: 980,
      ttfb_ms: 180,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 18,
      start_provider_name: "Claude Fast",
      final_provider_id: 18,
      final_provider_name: "Claude Fast",
      route: [{ provider_id: 18, provider_name: "Claude Fast", ok: true, status: 200 }],
      session_reuse: true,
      special_settings_json: buildClaudeModelMappingSpecialSettingsJson(claudeFastMapping),
      input_tokens: 86,
      output_tokens: 214,
      total_tokens: 300,
      cache_read_input_tokens: 2048,
      cache_creation_input_tokens: 0,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 86,
      cost_usd: 0.00618,
      cost_multiplier: 1,
      created_at_ms: null,
      created_at: nowSec - 45,
    },
    {
      id: 900009,
      trace_id: "preview-gemini-flash",
      cli_key: "gemini",
      session_id: null,
      method: "POST",
      path: "/v1/chat/completions",
      requested_model: "gemini-2.5-flash",
      status: 200,
      error_code: null,
      duration_ms: 1380,
      ttfb_ms: 260,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 17,
      start_provider_name: "Gemini Flash",
      final_provider_id: 17,
      final_provider_name: "Gemini Flash",
      route: [{ provider_id: 17, provider_name: "Gemini Flash", ok: true, status: 200 }],
      session_reuse: false,
      input_tokens: 124,
      output_tokens: 328,
      total_tokens: 452,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 124,
      cost_usd: 0.00392,
      cost_multiplier: 0.85,
      created_at_ms: null,
      created_at: nowSec - 70,
    },
    {
      id: 900008,
      trace_id: "preview-codex-failover",
      cli_key: "codex",
      session_id: "codex-preview-worktree",
      method: "POST",
      path: "/v1/responses",
      requested_model: "gpt-5.4",
      status: 200,
      error_code: null,
      duration_ms: 5220,
      ttfb_ms: 1260,
      attempt_count: 2,
      has_failover: true,
      start_provider_id: 15,
      start_provider_name: "Codex Pool A",
      final_provider_id: 16,
      final_provider_name: "Codex Pool B",
      route: [
        {
          provider_id: 15,
          provider_name: "Codex Pool A",
          ok: false,
          attempts: 1,
          status: 500,
          error_code: GatewayErrorCodes.UPSTREAM_5XX,
        },
        { provider_id: 16, provider_name: "Codex Pool B", ok: true, attempts: 1, status: 200 },
      ],
      session_reuse: false,
      input_tokens: 312,
      output_tokens: 462,
      total_tokens: 774,
      cache_read_input_tokens: 65536,
      cache_creation_input_tokens: 4096,
      cache_creation_5m_input_tokens: 4096,
      cache_creation_1h_input_tokens: 0,
      // codex semantics: cache_read covers the whole input, clamped to 0.
      effective_input_tokens: 0,
      cost_usd: 0.0,
      cost_multiplier: 1.15,
      created_at_ms: null,
      created_at: nowSec - 95,
    },
    {
      id: 900001,
      trace_id: "preview-claude",
      cli_key: "claude",
      session_id: "claude-preview-alpha",
      method: "POST",
      path: "/v1/messages",
      requested_model: "claude-sonnet-4",
      status: 200,
      error_code: null,
      duration_ms: 1640,
      ttfb_ms: 320,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 11,
      start_provider_name: "[F]Claude Main",
      final_provider_id: 11,
      final_provider_name: "[F]Claude Main",
      route: [],
      session_reuse: true,
      input_tokens: 138,
      output_tokens: 462,
      total_tokens: 600,
      cache_read_input_tokens: 4096,
      cache_creation_input_tokens: 0,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 138,
      cost_usd: 0.018245,
      cost_multiplier: 1,
      created_at_ms: null,
      created_at: nowSec - 120,
    },
    {
      id: 900002,
      trace_id: "preview-codex",
      cli_key: "codex",
      session_id: "codex-preview-main",
      method: "POST",
      path: "/v1/responses",
      requested_model: "gpt-5.4",
      status: 200,
      error_code: null,
      duration_ms: 6420,
      ttfb_ms: 1920,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 12,
      start_provider_name: "[F]CPA-Codex",
      final_provider_id: 12,
      final_provider_name: "[F]CPA-Codex",
      route: [{ provider_id: 12, provider_name: "[F]CPA-Codex", ok: true, status: 200 }],
      session_reuse: true,
      input_tokens: 179,
      output_tokens: 183,
      total_tokens: 362,
      cache_read_input_tokens: 157952,
      cache_creation_input_tokens: null,
      cache_creation_5m_input_tokens: null,
      cache_creation_1h_input_tokens: null,
      effective_input_tokens: 0,
      cost_usd: null,
      cost_multiplier: 0,
      created_at_ms: null,
      created_at: nowSec - 180,
    },
    {
      id: 900007,
      trace_id: "preview-claude-opus",
      cli_key: "claude",
      session_id: "claude-preview-beta",
      method: "POST",
      path: "/v1/messages",
      requested_model: "claude-opus-4",
      status: 200,
      error_code: null,
      duration_ms: 8440,
      ttfb_ms: 2200,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 19,
      start_provider_name: "Claude Opus",
      final_provider_id: 19,
      final_provider_name: "Claude Opus",
      route: [{ provider_id: 19, provider_name: "Claude Opus", ok: true, status: 200 }],
      session_reuse: true,
      input_tokens: 420,
      output_tokens: 910,
      total_tokens: 1330,
      cache_read_input_tokens: 32768,
      cache_creation_input_tokens: 8192,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 8192,
      effective_input_tokens: 420,
      cost_usd: 0.04462,
      cost_multiplier: 1.4,
      created_at_ms: null,
      created_at: nowSec - 255,
    },
    {
      id: 900006,
      trace_id: "preview-codex-timeout",
      cli_key: "codex",
      session_id: "codex-preview-main",
      method: "POST",
      path: "/v1/responses",
      requested_model: "gpt-5.4-mini",
      status: 504,
      error_code: GatewayErrorCodes.UPSTREAM_TIMEOUT,
      duration_ms: 12040,
      ttfb_ms: 0,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 20,
      start_provider_name: "Codex Timeout",
      final_provider_id: 20,
      final_provider_name: "Codex Timeout",
      route: [{ provider_id: 20, provider_name: "Codex Timeout", ok: false, status: 504 }],
      session_reuse: false,
      input_tokens: 144,
      output_tokens: 0,
      total_tokens: 144,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 144,
      cost_usd: 0.0,
      cost_multiplier: 1,
      created_at_ms: null,
      created_at: nowSec - 330,
    },
    {
      id: 900003,
      trace_id: "preview-gemini",
      cli_key: "gemini",
      session_id: null,
      method: "POST",
      path: "/v1/chat/completions",
      requested_model: "gemini-2.5-pro",
      status: 429,
      error_code: GatewayErrorCodes.PROVIDER_RATE_LIMITED,
      duration_ms: 2480,
      ttfb_ms: 1100,
      attempt_count: 2,
      has_failover: true,
      start_provider_id: 13,
      start_provider_name: "Gemini Pool",
      final_provider_id: 14,
      final_provider_name: "Gemini Mirror",
      route: [
        {
          provider_id: 13,
          provider_name: "Gemini Pool",
          ok: false,
          attempts: 1,
          status: 429,
          error_code: GatewayErrorCodes.PROVIDER_RATE_LIMITED,
        },
        { provider_id: 14, provider_name: "Gemini Mirror", ok: false, attempts: 1, status: 429 },
      ],
      session_reuse: false,
      input_tokens: 88,
      output_tokens: 0,
      total_tokens: 88,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 88,
      cost_usd: 0.0,
      cost_multiplier: 1.2,
      created_at_ms: null,
      created_at: nowSec - 420,
    },
    {
      id: 900005,
      trace_id: "preview-claude-abort",
      cli_key: "claude",
      session_id: "claude-preview-beta",
      method: "POST",
      path: "/v1/messages",
      requested_model: "claude-sonnet-4",
      status: 499,
      error_code: "GW_STREAM_ABORTED",
      duration_ms: 2120,
      ttfb_ms: 540,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 21,
      start_provider_name: "Claude Abort",
      final_provider_id: 21,
      final_provider_name: "Claude Abort",
      route: [{ provider_id: 21, provider_name: "Claude Abort", ok: false, status: 499 }],
      session_reuse: true,
      input_tokens: 0,
      output_tokens: 0,
      total_tokens: 0,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 0,
      cost_usd: 0.0,
      cost_multiplier: 1,
      created_at_ms: null,
      created_at: nowSec - 560,
    },
    {
      id: 900004,
      trace_id: "preview-gemini-free",
      cli_key: "gemini",
      session_id: null,
      method: "POST",
      path: "/v1/chat/completions",
      requested_model: "gemini-2.0-flash-exp",
      status: 200,
      error_code: null,
      duration_ms: 1720,
      ttfb_ms: 240,
      attempt_count: 1,
      has_failover: false,
      start_provider_id: 22,
      start_provider_name: "Gemini Free",
      final_provider_id: 22,
      final_provider_name: "Gemini Free",
      route: [{ provider_id: 22, provider_name: "Gemini Free", ok: true, status: 200 }],
      session_reuse: false,
      input_tokens: 102,
      output_tokens: 260,
      total_tokens: 362,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      cache_creation_5m_input_tokens: 0,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 102,
      cost_usd: null,
      cost_multiplier: 0,
      created_at_ms: null,
      created_at: nowSec - 780,
    },
    {
      id: 900011,
      trace_id: "preview-codex-retry",
      cli_key: "codex",
      session_id: "codex-preview-worktree",
      method: "POST",
      path: "/v1/responses",
      requested_model: "gpt-5.4",
      status: 200,
      error_code: null,
      duration_ms: 3880,
      ttfb_ms: 920,
      attempt_count: 3,
      has_failover: false,
      start_provider_id: 23,
      start_provider_name: "Codex Retry",
      final_provider_id: 23,
      final_provider_name: "Codex Retry",
      route: [
        { provider_id: 23, provider_name: "Codex Retry", ok: true, attempts: 3, status: 200 },
      ],
      session_reuse: true,
      input_tokens: 248,
      output_tokens: 540,
      total_tokens: 788,
      cache_read_input_tokens: 16384,
      cache_creation_input_tokens: 2048,
      cache_creation_5m_input_tokens: 2048,
      cache_creation_1h_input_tokens: 0,
      effective_input_tokens: 0,
      cost_usd: 0.01134,
      cost_multiplier: 1,
      created_at_ms: null,
      created_at: nowSec - 960,
    },
  ].map((item) => createRequestLogSummary(item));
}

export function buildPreviewTraces(nowMs = Date.now()): TraceSession[] {
  const claudeFailoverMapping = buildClaudeModelMappingPreview(
    "claude-sonnet-4",
    "gpt-5.4",
    "sonnet",
    32,
    "Claude Backup"
  );
  return [
    {
      trace_id: "preview-running-codex",
      cli_key: "codex",
      session_id: "codex-preview-main",
      method: "POST",
      path: "/v1/responses",
      query: null,
      requested_model: "gpt-5.4",
      first_seen_ms: nowMs - 18_000,
      last_seen_ms: nowMs,
      attempts: [
        {
          trace_id: "preview-running-codex",
          cli_key: "codex",
          method: "POST",
          path: "/v1/responses",
          query: null,
          attempt_index: 0,
          provider_id: 21,
          provider_name: "[F]CPA-Codex",
          base_url: "https://preview.local",
          outcome: "started",
          status: null,
          attempt_started_ms: nowMs - 18_000,
          attempt_duration_ms: 18_000,
          session_reuse: true,
        } satisfies GatewayAttemptEvent,
      ],
    },
    {
      trace_id: "preview-running-claude-failover",
      cli_key: "claude",
      session_id: "claude-preview-beta",
      method: "POST",
      path: "/v1/messages",
      query: null,
      requested_model: "claude-sonnet-4",
      claude_model_mapping: claudeFailoverMapping,
      first_seen_ms: nowMs - 52_000,
      last_seen_ms: nowMs - 1_200,
      attempts: [
        {
          trace_id: "preview-running-claude-failover",
          cli_key: "claude",
          method: "POST",
          path: "/v1/messages",
          query: null,
          attempt_index: 0,
          provider_id: 31,
          provider_name: "Claude Main",
          base_url: "https://preview.local",
          outcome: "failed",
          status: 529,
          attempt_started_ms: nowMs - 52_000,
          attempt_duration_ms: 21_000,
          session_reuse: false,
          claude_model_mapping: claudeFailoverMapping,
        } satisfies GatewayAttemptEvent,
        {
          trace_id: "preview-running-claude-failover",
          cli_key: "claude",
          method: "POST",
          path: "/v1/messages",
          query: null,
          attempt_index: 1,
          provider_id: 32,
          provider_name: "Claude Backup",
          base_url: "https://preview.local",
          outcome: "started",
          status: null,
          attempt_started_ms: nowMs - 29_000,
          attempt_duration_ms: 29_000,
          session_reuse: false,
          claude_model_mapping: claudeFailoverMapping,
        } satisfies GatewayAttemptEvent,
      ],
    },
    {
      trace_id: "preview-running-gemini-pending",
      cli_key: "gemini",
      session_id: null,
      method: "POST",
      path: "/v1/chat/completions",
      query: null,
      requested_model: "gemini-2.5-pro",
      first_seen_ms: nowMs - 7_000,
      last_seen_ms: nowMs - 2_500,
      attempts: [],
    },
  ];
}

export function buildPreviewSessionFolderLookups(): CliSessionsFolderLookupEntry[] {
  return [
    {
      source: "claude",
      session_id: "claude-preview-alpha",
      folder_name: "workspace-alpha",
      folder_path: "/Users/demo/workspace-alpha",
    },
    {
      source: "claude",
      session_id: "claude-preview-beta",
      folder_name: "workspace-beta",
      folder_path: "/Users/demo/workspace-beta",
    },
    {
      source: "codex",
      session_id: "codex-preview-main",
      folder_name: "platform-core",
      folder_path: "/Users/demo/platform-core",
    },
    {
      source: "codex",
      session_id: "codex-preview-worktree",
      folder_name: "platform-worktree",
      folder_path: "/Users/demo/platform-worktree",
    },
  ];
}
