//! Usage: Infrastructure adapters (filesystem paths, persistence, OS integration).

pub(crate) mod app_paths;
pub(crate) mod base_url_probe;
pub(crate) mod claude_hooks;
pub(crate) mod claude_settings;
pub(crate) mod cli_manager;
pub(crate) mod cli_proxy;
pub(crate) mod cli_update;
pub(crate) mod codex_config;
pub(crate) mod codex_paths;
pub(crate) mod codex_provider_sync;
pub(crate) mod config_migrate;
pub(crate) mod data_management;
pub(crate) mod db;
pub(crate) mod env_conflicts;
pub(crate) mod gemini_config;
pub(crate) mod mcp_sync;
pub(crate) mod model_price_aliases;
pub(crate) mod model_prices;
pub(crate) mod model_prices_sync;
pub(crate) mod plugins;
pub(crate) mod prompt_sync;
pub(crate) mod provider_circuit_breakers;
pub(crate) mod request_attempt_logs;
pub(crate) mod request_logs;
pub(crate) mod settings;
#[cfg_attr(not(windows), allow(dead_code, unused_imports))]
pub(crate) mod wsl;
